//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.13 at 07:32:42 PM IDT 
//


package xmls;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AddToAlbum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UserToAdd" type="{xsd}User"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addToAlbum",
    "userToAdd"
})
@XmlRootElement(name = "AddUserToAlbumRequestBody")
public class AddUserToAlbumRequestBody {

    @XmlElement(name = "AddToAlbum", required = true)
    protected String addToAlbum;
    @XmlElement(name = "UserToAdd", required = true)
    protected User userToAdd;

    /**
     * Gets the value of the addToAlbum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddToAlbum() {
        return addToAlbum;
    }

    /**
     * Sets the value of the addToAlbum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddToAlbum(String value) {
        this.addToAlbum = value;
    }

    /**
     * Gets the value of the userToAdd property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUserToAdd() {
        return userToAdd;
    }

    /**
     * Sets the value of the userToAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUserToAdd(User value) {
        this.userToAdd = value;
    }

}
