//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 08:39:05 PM IDT 
//


package xmls;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Albums" type="{xsd}AlbumsList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "albums"
})
@XmlRootElement(name = "GetAlbumsListResponseBody")
public class GetAlbumsListResponseBody {

    @XmlElement(name = "Albums", required = true)
    protected AlbumsList albums;

    /**
     * Gets the value of the albums property.
     * 
     * @return
     *     possible object is
     *     {@link AlbumsList }
     *     
     */
    public AlbumsList getAlbums() {
        return albums;
    }

    /**
     * Sets the value of the albums property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlbumsList }
     *     
     */
    public void setAlbums(AlbumsList value) {
        this.albums = value;
    }

}
