//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.04 at 07:58:55 PM IDT 
//


package xmls;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmls package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmls
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestMessage }
     * 
     */
    public RequestMessage createRequestMessage() {
        return new RequestMessage();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link NewAlbumRequestBody }
     * 
     */
    public NewAlbumRequestBody createNewAlbumRequestBody() {
        return new NewAlbumRequestBody();
    }

    /**
     * Create an instance of {@link CTAlbum }
     * 
     */
    public CTAlbum createCTAlbum() {
        return new CTAlbum();
    }

    /**
     * Create an instance of {@link NewAlbumResponseBody }
     * 
     */
    public NewAlbumResponseBody createNewAlbumResponseBody() {
        return new NewAlbumResponseBody();
    }

    /**
     * Create an instance of {@link NewUserRequestBody }
     * 
     */
    public NewUserRequestBody createNewUserRequestBody() {
        return new NewUserRequestBody();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link NewUserResponseBody }
     * 
     */
    public NewUserResponseBody createNewUserResponseBody() {
        return new NewUserResponseBody();
    }

    /**
     * Create an instance of {@link GetAlbumsListRequestBody }
     * 
     */
    public GetAlbumsListRequestBody createGetAlbumsListRequestBody() {
        return new GetAlbumsListRequestBody();
    }

    /**
     * Create an instance of {@link GetAlbumsListResponseBody }
     * 
     */
    public GetAlbumsListResponseBody createGetAlbumsListResponseBody() {
        return new GetAlbumsListResponseBody();
    }

    /**
     * Create an instance of {@link AlbumsList }
     * 
     */
    public AlbumsList createAlbumsList() {
        return new AlbumsList();
    }

    /**
     * Create an instance of {@link GetImageRequestBody }
     * 
     */
    public GetImageRequestBody createGetImageRequestBody() {
        return new GetImageRequestBody();
    }

    /**
     * Create an instance of {@link GetImageResponseBody }
     * 
     */
    public GetImageResponseBody createGetImageResponseBody() {
        return new GetImageResponseBody();
    }

    /**
     * Create an instance of {@link CTImage }
     * 
     */
    public CTImage createCTImage() {
        return new CTImage();
    }

    /**
     * Create an instance of {@link GetAlbumRequestBody }
     * 
     */
    public GetAlbumRequestBody createGetAlbumRequestBody() {
        return new GetAlbumRequestBody();
    }

    /**
     * Create an instance of {@link GetAlbumResponseBody }
     * 
     */
    public GetAlbumResponseBody createGetAlbumResponseBody() {
        return new GetAlbumResponseBody();
    }

    /**
     * Create an instance of {@link NewImageRequestBody }
     * 
     */
    public NewImageRequestBody createNewImageRequestBody() {
        return new NewImageRequestBody();
    }

    /**
     * Create an instance of {@link NewImageResponseBody }
     * 
     */
    public NewImageResponseBody createNewImageResponseBody() {
        return new NewImageResponseBody();
    }

    /**
     * Create an instance of {@link AddUserToAlbumRequestBody }
     * 
     */
    public AddUserToAlbumRequestBody createAddUserToAlbumRequestBody() {
        return new AddUserToAlbumRequestBody();
    }

    /**
     * Create an instance of {@link AddUserToAlbumResponseBody }
     * 
     */
    public AddUserToAlbumResponseBody createAddUserToAlbumResponseBody() {
        return new AddUserToAlbumResponseBody();
    }

    /**
     * Create an instance of {@link UpdateRulesRequestBody }
     * 
     */
    public UpdateRulesRequestBody createUpdateRulesRequestBody() {
        return new UpdateRulesRequestBody();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link UpdateRulesResponseBody }
     * 
     */
    public UpdateRulesResponseBody createUpdateRulesResponseBody() {
        return new UpdateRulesResponseBody();
    }

    /**
     * Create an instance of {@link UpdateUserProfileRequestBody }
     * 
     */
    public UpdateUserProfileRequestBody createUpdateUserProfileRequestBody() {
        return new UpdateUserProfileRequestBody();
    }

    /**
     * Create an instance of {@link UpdateUserProfileResponseBody }
     * 
     */
    public UpdateUserProfileResponseBody createUpdateUserProfileResponseBody() {
        return new UpdateUserProfileResponseBody();
    }

    /**
     * Create an instance of {@link LoginRequestBody }
     * 
     */
    public LoginRequestBody createLoginRequestBody() {
        return new LoginRequestBody();
    }

    /**
     * Create an instance of {@link LoginResponseBody }
     * 
     */
    public LoginResponseBody createLoginResponseBody() {
        return new LoginResponseBody();
    }

    /**
     * Create an instance of {@link DummyObject }
     * 
     */
    public DummyObject createDummyObject() {
        return new DummyObject();
    }

    /**
     * Create an instance of {@link CTThumbnail }
     * 
     */
    public CTThumbnail createCTThumbnail() {
        return new CTThumbnail();
    }

    /**
     * Create an instance of {@link CTAlbumPreview }
     * 
     */
    public CTAlbumPreview createCTAlbumPreview() {
        return new CTAlbumPreview();
    }

}
